SELECT TIME_ID, DAY_NAME, CALENDAR_MONTH_NAME, CALENDAR_YEAR FROM SH.TIMES WHERE CALENDAR_YEAR = 2000;

SELECT * FROM SH.TIMES WHERE CALENDAR_MONTH_NAME = 'DECEMBER'  AND CALENDAR_YEAR = 2001;
 
SELECT PROD_ID, TIME_ID, UNIT_COST, UNIT_PRICE FROM SH.COSTS WHERE UNIT_PRICE > UNIT_COST;

SELECT * FROM SH.COSTS WHERE UNIT_COST > 100 AND UNIT_PRICE < 1000;

SELECT CUST_ID, EDUCATION, OCCUPATION, HOUSEHOLD_SIZE FROM SH.SUPPLEMENTARY_DEMOGRAPHICS WHERE HOUSEHOLD_SIZE > 3;
